get_target_property(core_sources ce_psvaml_core SOURCES)
list(TRANSFORM core_sources PREPEND "${PROJECT_SOURCE_DIR}/")
add_library(ce_psvaml_test_core STATIC ${core_sources})
target_include_directories(ce_psvaml_test_core PUBLIC ${PROJECT_SOURCE_DIR}/src ${raylib_SOURCE_DIR}/src)
target_compile_definitions(ce_psvaml_test_core PUBLIC CE_TESTING)
add_executable(ce_psvaml_tests TestMain.cpp CoreTests.cpp WorldTests.cpp PhysicsTests.cpp PhysiologyTests.cpp SensoryTests.cpp NervousSystemTests.cpp LearningTests.cpp DevelopmentTests.cpp GenomeTests.cpp ReproductionTests.cpp WormTests.cpp PopulationTests.cpp ScenarioTests.cpp SimulationTests.cpp MetricsTests.cpp CommandLineTests.cpp)
target_link_libraries(ce_psvaml_tests PRIVATE ce_psvaml_test_core Catch2::Catch2WithMain)
include(Catch)
catch_discover_tests(ce_psvaml_tests)
